templify/donation/routes.py
from flask import Blueprint, render_template, request, jsonify, url_for
from templify.models import Donation

donation = Blueprint('donation', __name__)


@donation.route('/donation', methods=['GET', 'POST'])
def donation_page():
    if request.method == 'POST':
        data = request.json
        trans_id = Donation.save_donation(data)
        return url_for('donation.dono_bill', donation_id=str(trans_id), _external=True)
    return render_template('donation.html')


@donation.route('/dono_bill/<donation_id>')
def dono_bill(donation_id):
    info = Donation.get_donation(donation_id)
    return render_template('dono_bill.html', info=info)

templify/kettunira/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from templify.models import Kettunira

kettunira = Blueprint('kettunira', __name__)


@kettunira.route('/kettunira', methods=['GET', 'POST'])
def kettunira_page():
    if request.method == 'POST':
        data=request.json
        trans_id = Kettunira.save_kettunira(data)
        return url_for('kettunira.kettu_bill', kettu_id=str(trans_id), _external=True)
    return render_template('kettunira.html')


@kettunira.route('/kettu_bill/<kettu_id>')
def kettu_bill(kettu_id):
    info = Kettunira.get_kettunira(kettu_id)
    return render_template('kettu_bill.html', info=info)

templify/main/routes.py
from flask import Blueprint, send_from_directory, redirect, url_for

main = Blueprint('main', __name__)


@main.route('/<path:path>')
def catch_all(path):
    return send_from_directory('static', path)


@main.route('/')
def index():
    return redirect(url_for('seva.seva_page'))

templify/seva/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from templify.models import Seva
seva = Blueprint('seva', __name__)


@seva.route('/seva', methods=['GET', 'POST'])
def seva_page():
    if request.method == 'POST':
        data = request.json
        trans_id = Seva.save_seva(data)
        return url_for('seva.bill', t_id=str(trans_id), _external=True)
    pooja_list = Seva.get_poojas()
    pooja_list.sort(key=lambda x: x['Pooja'].lower())
    return render_template('seva.html', poojas=pooja_list)


@seva.route('/seva/<pooja_id>')
def get_gods(pooja_id):
    gods = Seva.get_gods(pooja_id)
    return jsonify(gods)


@seva.route('/bill/<t_id>')
def bill(t_id):
    info = Seva.get_seva(t_id)
    # get unique gods
    gods = []
    for pooja in info['poojas']:
        pooja['price'] = Seva.get_price(pooja['pooja_id'])
        if pooja['god'] not in gods:
            gods.append(pooja['god'])
    info['gods'] = gods
    # get god wise poojas
    god_wise_poojas = {}
    for god in gods:
        poojas = []
        for pooja in info['poojas']:
            if pooja['god'] == god:
                poojas.append(pooja)
        god_wise_poojas[god] = poojas
    info['god_wise_poojas'] = god_wise_poojas
    print(info)
    return render_template('bill.html', info=info)

templify/transactions/routes.py
from flask import Blueprint, render_template, request, jsonify
from templify.models import Transaction

transactions = Blueprint('transactions', __name__)


@transactions.route('/transactions', methods=['GET', 'POST'])
def transactions_page():
    if request.method == 'POST':
        data = request.data.decode('utf-8')
        transaction_list = []
        if data == 'seva':
            transaction_list = Transaction.get_sevas()
        elif data == 'donation':
            transaction_list = Transaction.get_donations()
        elif data == 'daily_date':
            dates = Transaction.get_daily_dates()
            return jsonify(dates)
        else:
            transaction_list = Transaction.get_transactions(data)

        return jsonify(transaction_list)
    return render_template('transactions.html')

templify/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Templify</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('main.catch_all', path='bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('main.catch_all', path='style.css') }}">
    <script src="{{ url_for('main.catch_all', path='bootstrap/js/bootstrap.min.js') }}"></script>
    {% block links %}
    {% endblock %}
</head>
    <!-- Cashier portal  this is the main page-->
<body>
    <nav class="navbar navbar-light navbar-expand-md py-3 hidden-print" style="height: 15vh;border-bottom: solid orange">
        <div class="container-fluid"><a class="navbar-brand d-flex align-items-center" href="{{ url_for('seva.seva_page') }}">
            <img src="{{ url_for('main.catch_all', path='images/logo.png') }} " width="217" height="92" /></a><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navcol-2"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div id="navcol-2" class="collapse navbar-collapse">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('seva.seva_page') }}">Seva</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('donation.donation_page') }}">Donation</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('kettunira.kettunira_page') }}">Kettunira</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('transactions.transactions_page') }}"><span style="color: var(--bs-nav-link-hover-color);">Transactions</span></a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container" style="max-width: 100vw;min-height: 85vh;background: linear-gradient(-154deg, #FF930F, #FFF95B 85%);">
        <div class="row" style="justify-content: space-between">
{#            <div class="col-md-4 col-lg-2 offset-lg-0">#}
{#                <img src="{{ url_for('main.catch_all', path='images/flower.png') }}" width="60%">#}
{#            </div>#}
            <div class="col-md-4 col-lg-2 offset-lg-0 hidden-print">
                <div class="pendulum-holder">
                    <img class="pendulum" src="{{ url_for('main.catch_all', path='images/diyaonly.png') }}" height="100%" width="5em" alt="diya">
                </div>
            </div>
            <div class="col-md-8 col-lg-8">
{#                <h2 style="text-align: center;margin-bottom: 1.4em">Seva Receipt</h2>#}
{#                <form style="border-color: var(--bs-danger);margin: 0.6em;">#}
{#                    <div>#}
{#                        <select id="god" class="form-select" style="margin-bottom: 2em;" required>#}
{#                            <option value="Ayyappan" selected>Ayyappan</option>#}
{#                            <option value="Ganapati">Ganapati</option>#}
{#                            <option value="Devi">Devi</option>#}
{#                            <option value="Naga">Naga</option>#}
{#                            <option value="Navagraha">Navagraha</option>#}
{#                        </select>#}
{#                        <input class="form-control" type="text" name="Name" placeholder="Name" style="margin-bottom: 2em;" required/>#}
{#                        <select id="star" class="form-select" style="margin-bottom: 2em;" required>#}
{#                            <option value="Aswathi">Aswathi</option>#}
{#                            <option value="Bharani">Bharani</option>#}
{#                            <option value="Kaarthika">Kaarthika</option>#}
{#                            <option value="Rohini">Rohini</option>#}
{#                            <option value="Makeeryam">Makeeryam</option>#}
{#                            <option value="Thiruvaathira">Thiruvaathira</option>#}
{#                            <option value="Punartham">Punartham</option>#}
{#                            <option value="Aayilyam">Aayilyam</option>#}
{#                            <option value="Makam">Makam</option>#}
{#                            <option value="Pooram">Pooram</option>#}
{#                            <option value="Uthram">Uthram</option>#}
{#                            <option value="Atham">Atham</option>#}
{#                            <option value="Chitra">Chitra</option>#}
{#                            <option value="Chothi">Chothi</option>#}
{#                            <option value="Visakham">Visakham</option>#}
{#                            <option value="Anizham">Anizham</option>#}
{#                            <option value="Thrikketta">Thrikketta</option>#}
{#                            <option value="Moolam">Moolam</option>#}
{#                            <option value="Pooradam">Pooradam</option>#}
{#                            <option value="Uthradam">Uthradam</option>#}
{#                            <option value="Thiruvonam">Thiruvonam</option>#}
{#                            <option value="Avittam">Avittam</option>#}
{#                            <option value="Chathayam">Chathayam</option>#}
{#                            <option value="Poorattadhi">Poorattadhi</option>#}
{#                            <option value="Uthrattadhi">Uthrattadhi</option>#}
{#                            <option value="Revathi">Revathi</option>#}
{#                        </select>#}
{#                        <select id="pooja" class="form-select" style="margin-bottom: 2em" required multiple>#}
{#                            <option value="archana">Archana</option>#}
{#                        </select>#}
{#                        <input class="form-control" type="date" style="margin-bottom: 2em">#}
{#                    </div>#}
{#                    <div class="d-md-flex justify-content-md-center align-items-md-center">#}
{#                        <button class="btn btn-primary" type="submit">Save</button>#}
{#                        <button class="btn btn-primary" type="button" style="margin-right: 0px;margin-left: 103px;">Print</button></div>#}
{#                </form>#}
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-md-4 col-lg-2 offset-lg-0 hidden-print">
                <div class="pendulum-holder">
                    <img class="pendulum-reverse" src="{{ url_for('main.catch_all', path='images/diyaonly.png') }}" height="10em" width="5em" alt="diya">
                </div>
            </div>
{#            <div class="col-md-4 col-lg-2 offset-lg-0">#}
{#                <img src="{{ url_for('main.catch_all', path='images/flower.png') }}" width="60%">#}
{#            </div>#}
        </div>
    </div>
</body>
</html>

templify/templates/bill.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="{{ url_for('main.catch_all', path='bill.css') }}" rel="stylesheet">
        <title>Receipt</title>
    </head>
    <body>
        {% for god in info['god_wise_poojas'].keys() %}
            <div class="ticket">
                <p class="centered">SRI AYYAPPA SWAMY TEMPLE
                    <br>Hebbal Kempapura, Bengaluru
                    <br>Name: {{ info['name'] }}
                    <br>Nakshatra: {{ info['star'] }}
                    {% if god != '' %}
                        <br>God: {{ god }}
                    {% endif %}
                    <br>Date: {{ info['seva_date'] }}
{#                    <br>Transaction Id:#}
{#                    <br>{{ info['_id'] }}</p>#}
                <table>
                    <thead>
                        <tr>
                            <th class="quantity">Sl.no.</th>
                            <th class="description">Pooja</th>
                            <th class="price">Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% set count = namespace(value=1) %}
                        {% for pooja in info['god_wise_poojas'][god] %}
                            <tr>
                                <td class="quantity">{{ count.value }}</td>
                                <td class="description">{{ pooja['pooja'] }}</td>
                                <td class="price">{{ pooja['price'] }}</td>
                            </tr>
                            {% set count.value = count.value + 1 %}
                        {% endfor %}
                    </tbody>
                </table>
                <p class="centered">Thanks for visiting!
                    <br>Templify</p>
            </div>
            <hr style="color: black;border: solid black;text-align: left;width: 155px;margin-left: 0">
        {% endfor %}
        <button id="btnPrint" class="hidden-print">Print</button>
        <script src="{{ url_for('main.catch_all', path='js/bill.js') }}"></script>
    </body>
</html>

templify/templates/donation.html
{% extends 'base.html' %}

{% block content %}
    <h2 style="text-align: center;margin-bottom: 1.4em">Donation Receipt</h2>
    <form style="border-color: var(--bs-danger);margin: 0.6em;">
        <input id="name" class="form-control" type="text" name="Name" placeholder="Name" style="margin-bottom: 2em;" required/>
        <select id="donation_type" class="form-select" style="margin-bottom: 2em;" required>
            <option value="donation">Donation</option>
            <option value="annadanam">Annadanam</option>
        </select>
        <input id="amount" class="form-control" type="number" name="Amount" placeholder="Amount" style="margin-bottom: 2em;" required/>
        <input id="donation_date" class="form-control" type="date" name="Date" placeholder="Date" style="margin-bottom: 2em;" required />
        <div style="display: flex;justify-content: center">
            <a onclick="submitDonation()" class="btn btn-primary">Save</a>
        </div>
    </form>
    <script src="{{ url_for('main.catch_all', path='js/donation.js') }}"></script>
{% endblock %}

templify/templates/dono_bill.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="{{ url_for('main.catch_all', path='bill.css') }}" rel="stylesheet">
        <title>Receipt</title>
    </head>
    <body>
    <div class="ticket">
            <p class="centered">SRI AYYAPPA SWAMY TEMPLE
                <br>Hebbal Kempapura, Bengaluru
                <br>Name: {{ info['name'] }}
                <br>Date: {{ info['donation_date'] }}
                <br>Transaction Id:
                <br>{{ info['_id'] }}</p>
            <table>
                <thead>
                    <tr>
                        <th class="quantity">Sl.no.</th>
                        <th class="description">Type</th>
                        <th class="price">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% set count = 1 %}
                    <tr>
                        <td class="quantity">{{ count }}</td>
                        <td class="description">{{ info['donation_type'] }}</td>
                        <td class="price">{{ info['amount'] }}</td>
                    </tr>
                </tbody>
            </table>
            <p class="centered">Thanks for visiting!
                <br>Templify</p>
        </div>
        <hr style="color: black;border: solid black;text-align: left;width: 155px;margin-left: 0">
        <button id="btnPrint" class="hidden-print">Print</button>
        <script src="{{ url_for('main.catch_all', path='js/bill.js') }}"></script>
    </body>
</html>

templify/templates/kettu_bill.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="{{ url_for('main.catch_all', path='bill.css') }}" rel="stylesheet">
        <title>Receipt</title>
    </head>
    <body>
    <div class="ticket">
            <p class="centered">SRI AYYAPPA SWAMY TEMPLE
                <br>Hebbal Kempapura, Bengaluru
                <br>Name: {{ info['name'] }}
                <br>Date: {{ info['kettunira_date'] }}
                <br>Transaction Id:
                <br>{{ info['_id'] }}</p>
            <table>
                <thead>
                    <tr>
                        <th class="quantity">Sl.no.</th>
                        <th class="description">Type</th>
                        <th class="quantity">No.Per.</th>
                        <th class="price">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% set count = 1 %}
                    <tr>
                        <td class="quantity">{{ count }}</td>
                        <td class="description">Kettunira</td>
                        <td class="quantity">{{ info['n_of_persons'] }}</td>
                        <td class="price">{{ info['total'] }}</td>
                    </tr>
                </tbody>
            </table>
            <p class="centered">Thanks for visiting!
                <br>Templify</p>
        </div>
        <hr style="color: black;border: solid black;text-align: left;width: 155px;margin-left: 0">
        <button id="btnPrint" class="hidden-print">Print</button>
        <script src="{{ url_for('main.catch_all', path='js/bill.js') }}"></script>
    </body>
</html>

templify/templates/kettunira.html
{% extends 'base.html' %}

{% block content %}
    <h2 style="text-align: center;margin-bottom: 1.4em">Kettunira</h2>
    <form style="border-color: var(--bs-danger);margin: 0.6em;" >
        <input id="name" class="form-control" type="text" name="Name" placeholder="Name" style="margin-bottom: 2em;" required/>
        <input id="n_of_persons" class="form-control" type="number" name="Number_Of_Persons" placeholder="Number_Of_Persons" style="margin-bottom: 2em;" required/>
        <input id="kettunira_date" class="form-control" type="date" style="margin-bottom: 2em">
        <div style="display: flex;justify-content: center">
            <a onclick="submitKettunira()" class="btn btn-primary">Save</a>
        </div>
    </form>
    <script src="{{ url_for('main.catch_all', path='js/kettunira.js') }}"></script>
{% endblock %}

templify/templates/seva.html
{% extends 'base.html' %}

{% block content %}
    <h2 style="text-align: center;margin-bottom: 1.4em">Seva Receipt</h2>
    <form style="border-color: var(--bs-danger);margin: 0.6em;" >
        <div>
            <input id="name" class="form-control" type="text" name="Name" placeholder="Name" style="margin-bottom: 2em;" required/>
            <select id="star" class="form-select" style="margin-bottom: 2em;" required>
                <option value="Aswathi">Aswathi</option>
                <option value="Bharani">Bharani</option>
                <option value="Kaarthika">Kaarthika</option>
                <option value="Rohini">Rohini</option>
                <option value="Makeeryam">Makeeryam</option>
                <option value="Thiruvaathira">Thiruvaathira</option>
                <option value="Punartham">Punartham</option>
                <option value="Aayilyam">Aayilyam</option>
                <option value="Makam">Makam</option>
                <option value="Pooram">Pooram</option>
                <option value="Uthram">Uthram</option>
                <option value="Atham">Atham</option>
                <option value="Chitra">Chitra</option>
                <option value="Chothi">Chothi</option>
                <option value="Visakham">Visakham</option>
                <option value="Anizham">Anizham</option>
                <option value="Thrikketta">Thrikketta</option>
                <option value="Moolam">Moolam</option>
                <option value="Pooradam">Pooradam</option>
                <option value="Uthradam">Uthradam</option>
                <option value="Thiruvonam">Thiruvonam</option>
                <option value="Avittam">Avittam</option>
                <option value="Chathayam">Chathayam</option>
                <option value="Poorattadhi">Poorattadhi</option>
                <option value="Uthrattadhi">Uthrattadhi</option>
                <option value="Revathi">Revathi</option>
            </select>
            <input id="seva_date" class="form-control" type="date" style="margin-bottom: 2em">
        </div>
        <div class="card-group" style="margin-top: 2em;margin-bottom: 2em;">
            <div class="card" style="background: transparent;border-radius: 0.3em;border-width: 0.3em;border-color: orange;">
                <div class="card-body">
                    <h4 class="card-title">
                        <select id="pooja" class="form-select">
                            {% set price=[] %}
                            {% set pooja_list=[] %}
                            {% for pooja in poojas %}
                                <option value="{{ pooja['_id'] }}">{{ pooja['Pooja'] }}</option>
                                {% set price=price.append(pooja['Price']) %}
                                {% set pooja_list=pooja_list.append(pooja['Pooja']) %}
                            {% endfor %}
                        </select>
                    </h4>
                    <div class="flex align-content-center justify-content-md-center">
                        <select id="gods" class="form-select" style="margin-bottom: 2em;margin-top: 2em;"></select>
                        <div style="display: flex;justify-content: center">
                            <button id="add" class="btn btn-primary" type="button">Add</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="table-responsive" style="margin-bottom: 2em">
            <table class="table">
                <thead>
                    <tr>
                        <th>Pooja</th>
                        <th>Price</th>
                        <th>God</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody id="added_poojas">
                </tbody>
                <tfoot>
                    <tr>
                        <th>Total</th>
                        <th id="total">0</th>
                        <th></th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="d-md-flex justify-content-md-center align-items-md-center">
            <a onclick="submitSeva()" class="btn btn-primary">Save</a>
        </div>
    </form>
    <script src="{{ url_for('static', filename='js/seva.js') }}"
            prices_list="{{ price|tojson }}"
            delete_icon={{ url_for('main.catch_all', path='images/remove.png')|tojson }}></script>
{% endblock %}

templify/templates/transactions.html
{% extends 'base.html' %}

{% block links %}
    <link rel="stylesheet" href="{{ url_for('main.catch_all', path='transaction.css') }}">
{% endblock %}

{% block content %}
    <h2 style="text-align: center;margin-bottom: 1.4em" class="hidden-print">Transactions</h2>
    <select id="type" class="form-select hidden-print" style="margin-bottom: 2em;">
        <option value="seva">All Seva</option>
        <option value="donation">All Donation</option>
        <option value="daily">Day report</option>
    </select>
    <div id="day_select" class="hidden-print"></div>
    <div class="table-responsive" style="margin-bottom: 2em">
        <table class="table">
            <thead id="t_head">
            </thead>
            <tbody id="transactions">
            </tbody>
        </table>
    </div>
    <button id="btnPrint" class="hidden-print">Print</button>
    <script src="{{ url_for('main.catch_all', path='js/transaction.js') }}"></script>
{% endblock %}